### ISSUE TITLE
[Bug] Refresh throws Attribute Error

### ISSUE THREAD

**Issue by Dracon23** [earshel/PokeyPyManager#12]
Traceback: [Gist](https://gist.github.com/f070a458365f317ef40296d72932c6d4)
Latest changeset

Reproduce this:
Click refresh on inventory

**Comment by earshel** [comment]
I haven't been able to reproduce this error. Is it happening consistently?

**Comment by Dracon23** [comment]
Yes... Been pulling in a fresh clone as well.. I'm running this behind an nginx reverse proxy,, might be an issue as well.

**Comment by earshel** [comment]
I'm not familiar with nginx. I haven't been able to reproduce this error. Just fixed the rate limiting error though. ;)

**Comment by RenatoKR** [comment]
Same problem under W10 local machine

**Comment by earshel** [comment]
@ShadyBS  using the most recent commit, have you seen this problem?

**Comment by RenatoKR** [comment]
@earshel 
just updated, here is what i get on my console:
`Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Python27\lib\site-packages\flask\app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Renato\Desktop\PokeBots\PokeyPyManager\mgr.py", line 252, in index
    stats = session.getInventory().stats
  File "C:\Users\Renato\Desktop\PokeBots\PokeyPyManager\pogo\session.py", line 58, in getInventory
    self.getProfile()
  File "C:\Users\Renato\Desktop\PokeBots\PokeyPyManager\pogo\session.py", line 44, in getProfile
    res = self.wrapAndRequest(payload)
  File "C:\Users\Renato\Desktop\PokeBots\PokeyPyManager\pogo\session_bare.py", line 286, in wrapAndRequest
    res = self.request(self.wrapInRequest(payload, defaults=defaults))
  File "C:\Users\Renato\Desktop\PokeBots\PokeyPyManager\pogo\session_bare.py", line 233, in wrapInRequest
    signature = hashSignature(proto, self.encryptLib)
  File "C:\Users\Renato\Desktop\PokeBots\PokeyPyManager\pogo\util.py", line 124, in hashSignature
    library = ctypes.cdll.LoadLibrary(libraryPath)
  File "C:\Python27\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application`

**Comment by earshel** [comment]
Check your config.ini. Make sure you have indicated the correct encrypt.dll. If it's currently set to encrypt32bit.dll change it to 64, or the opposite ;)
