### ISSUE TITLE
Error in Periodic call to getMapObjects to keep connection alive

### ISSUE THREAD

**Issue by Kitryn** [earshel/PokeyPyManager#6]
While transferring pokemon, server initally ran into the following error:

```
Line 123,base.py - 2016-08-11 22:46:21,018 - INFO - Running job "Periodic call to getMapObjects to keep connection alive (trigger: interval[0:00:30], next run at: 2016-08-11 22:46:51 SGT)" (scheduled at 2016-08-11 22:46:21.015943+08:00)
Line 224,session_bare.py - 2016-08-11 22:46:21,321 - ERROR - status_code: 102

Line 131,base.py - 2016-08-11 22:46:21,322 - ERROR - Job "Periodic call to getMapObjects to keep connection alive (trigger: interval[0:00:30], next run at: 2016-08-11 22:46:51 SGT)" raised an exception
Traceback (most recent call last):
  File "/Users/FoxtailSoup/.virtualenvs/pogom/lib/python2.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "mgr.py", line 280, in hb
    hb = session.getMapObjects()
  File "/Users/FoxtailSoup/Dropbox/scripts/PokeyPyManager/pogo/session.py", line 100, in getMapObjects
    res = self.wrapAndRequest(payload)
  File "/Users/FoxtailSoup/Dropbox/scripts/PokeyPyManager/pogo/session_bare.py", line 183, in wrapAndRequest
    self.parseDefault(res)
  File "/Users/FoxtailSoup/Dropbox/scripts/PokeyPyManager/pogo/session_bare.py", line 225, in parseDefault
    raise PogoResponseException("Expected response not returned")
PogoResponseException: Expected response not returned
```

This is followed by:

```
Line 1587,app.py - 2016-08-11 22:46:23,771 - ERROR - Exception on /release [GET]
Traceback (most recent call last):
  File "/Users/FoxtailSoup/.virtualenvs/pogom/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/FoxtailSoup/.virtualenvs/pogom/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/FoxtailSoup/.virtualenvs/pogom/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/FoxtailSoup/.virtualenvs/pogom/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/FoxtailSoup/.virtualenvs/pogom/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "mgr.py", line 83, in release
    logging.critical(session.releasePokemon(inventory.party[poke]))
  File "/Users/FoxtailSoup/Dropbox/scripts/PokeyPyManager/pogo/session.py", line 302, in releasePokemon
    self._state.release.ParseFromString(res.returns[0])
  File "/Users/FoxtailSoup/.virtualenvs/pogom/lib/python2.7/site-packages/google/protobuf/internal/containers.py", line 204, in __getitem__
    return self._values[key]
IndexError: list index out of range
```

and also:

```
Line 1587,app.py - 2016-08-11 22:46:29,244 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/FoxtailSoup/.virtualenvs/pogom/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/FoxtailSoup/.virtualenvs/pogom/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/FoxtailSoup/.virtualenvs/pogom/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/FoxtailSoup/.virtualenvs/pogom/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/FoxtailSoup/.virtualenvs/pogom/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "mgr.py", line 207, in index
    stats = session.getInventory().stats
  File "/Users/FoxtailSoup/Dropbox/scripts/PokeyPyManager/pogo/session.py", line 40, in getInventory
    self.getProfile()
  File "/Users/FoxtailSoup/Dropbox/scripts/PokeyPyManager/pogo/session.py", line 73, in getProfile
    res = self.wrapAndRequest(payload)
  File "/Users/FoxtailSoup/Dropbox/scripts/PokeyPyManager/pogo/session_bare.py", line 183, in wrapAndRequest
    self.parseDefault(res)
  File "/Users/FoxtailSoup/Dropbox/scripts/PokeyPyManager/pogo/session_bare.py", line 225, in parseDefault
    raise PogoResponseException("Expected response not returned")
PogoResponseException: Expected response not returned
```

The last error then continuously repeats until I shut the server down. I have not tried reproducing this error. Will update if I run into it again.

System: OSX

**Comment by earshel** [comment]
This seems to happen randomly. It's happening when we receive a response from the server that we didn't expect. I haven't had a chance to dig any deeper, but I plan to :)
